package com.hillel.hrebeniev.homeworks.homework_27_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 */
@WebService(name = "OrderService", targetNamespace = "http://service.hillel.edu/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface OrderService {

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.AddResponse")
    @Action(input = "http://service.hillel.edu/OrderService/addRequest", output = "http://service.hillel.edu/OrderService/addResponse")
    public void add(
            @WebParam(name = "arg0", targetNamespace = "")
            Order arg0);

    /**
     * @param arg0
     * @return returns edu.hillel.client.generated.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.GetByIdResponse")
    @Action(input = "http://service.hillel.edu/OrderService/getByIdRequest", output = "http://service.hillel.edu/OrderService/getByIdResponse")
    public Order getById(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * @return returns java.util.List<edu.hillel.client.generated.Order>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.hillel.edu/", className = "com.hillel.hrebeniev.homeworks.homework_27_client.GetAllResponse")
    @Action(input = "http://service.hillel.edu/OrderService/getAllRequest", output = "http://service.hillel.edu/OrderService/getAllResponse")
    public List<Order> getAll();

}